name: jogodocalebao
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.1
  gap: ^3.0.1
  mobx: ^2.3.3+2
  cloud_firestore: ^4.17.4
  firebase_core: ^2.31.1

dev_dependencies:
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true