// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:jogodocalebao/core/env_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: EnvironmentConfig.googleApiKey,
    appId: '1:321405619998:web:27c567c68b64fd7903030f',
    messagingSenderId: '321405619998',
    projectId: 'jogodocalebao',
    authDomain: 'jogodocalebao.firebaseapp.com',
    storageBucket: 'jogodocalebao.appspot.com',
    measurementId: 'G-TVPQXE9S2N',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: EnvironmentConfig.googleApiKey,
    appId: '1:321405619998:android:a5b343e18ffb5dac03030f',
    messagingSenderId: '321405619998',
    projectId: 'jogodocalebao',
    storageBucket: 'jogodocalebao.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: EnvironmentConfig.googleApiKey,
    appId: '1:321405619998:ios:f670a1c6f69f108a03030f',
    messagingSenderId: '321405619998',
    projectId: 'jogodocalebao',
    storageBucket: 'jogodocalebao.appspot.com',
    iosBundleId: 'com.calebgp.jogodocalebao',
  );
}
